Align readme format
runtastic/health_monitor pull request #5
Opened 2018-11-14 13:41 UTC by Goltergaul

2018-11-14 15:06 UTC, nilsding commented on CODE_OF_CONDUCT.md
> +# Contributor Covenant Code of Conduct
❤️

2018-11-14 15:12 UTC, nilsding requested changes
Generally nice, just some minor formatting things.

2018-11-14 15:12 UTC, nilsding commented on README.md
> +Add the middleware to your config.ru
Please wrap file names with backticks `so they show up like this`

2018-11-14 15:12 UTC, nilsding commented on README.md
> +needs to return the result of the /healthmonitor endpoint of the other service:
By default, this gem mounts itself to `/health_monitor`.  Please update this + the example according to that, and wrap the path in backticks

2018-11-14 15:12 UTC, nilsding commented on README.md
> +After checking out the repo, run `bin/setup` to install dependencies. You can also run `bin/console` for an interactive prompt that will allow you to experiment.
Please wrap the lines at around 80 characters.

2018-11-14 15:26 UTC, nilsding commented on README.md
> +needs to return the result of the /health_monitor endpoint of the other service:
Backticks ;-) 

```suggestion
needs to return the result of the `/health_monitor` endpoint of the other service:
```

2018-11-14 15:33 UTC, nilsding approved these changes

2018-11-14 15:34 UTC, merged

2018-11-15 07:31 UTC, Goltergaul commented
does github do autosquash on merge?

2018-11-15 09:59 UTC, nilsding commented
Don't think so, but it can do squash merges.